### ISSUE TITLE
Remove request in Angular index.html to material icons - this could be causing the slowdown

### ISSUE THREAD

**Issue by InBrewJ** [LUSHDigital/lrpi_player#102]

**Comment by InBrewJ** [comment]
@pisuke This is _exactly_ what's causing the slowdown. Well spotted!

Super simple fix. I'll look into the rest of the issues tomorrow - I had a slow start today because of some ssh issues

**Comment by pisuke** [comment]
@InBrewJ no worries, thanks for checking! And glad you think this is the cause of the slowdown.
@bungeejim was of the opinion the SRT size is also an issue, so I'll have a look at it too, unless you're 100% the SRT size is a red herring ...

**Comment by InBrewJ** [comment]
@pisuke The SRT size is definitely affecting performance but it's no longer compounded by the timeout caused by this error. I'm still digging though :)

**Comment by pisuke** [comment]
@InBrewJ I've dug deeper today, and the 60 MB file load up in about 18 seconds. 
I've managed to reduce the SRT loading time to 12 seconds with file optimisation.
This amount of time seems manageable, but to improve this we'll have to either consider switching to a binary format or use the streaming functionality in pysrt.

**Comment by InBrewJ** [comment]
Full disclosure, I hadn't _actually_ started digging yet. Seems like great steps though 💪 

This sort of streaming stuff?

https://kite.com/python/docs/pysrt.stream
https://github.com/byroot/pysrt/blob/master/pysrt/srtfile.py#L181

**Comment by pisuke** [comment]
Yup, I had a quick [discussion with Jean](https://github.com/byroot/pysrt/issues/79) and he suggested to have a look at the streaming function, and perhaps do some profiling too.
I did try a [direct replacement of open with stream](https://github.com/LUSHDigital/lrpi_player/blob/756cd7549af83dab71d7c0bdcb555ebb4bf3c1fe/flask/Server.py#L262) but it didn't work as it is based on a python generator. It really needs incremental reading, so I'm thinking of trying next to add a thread that goes through the stream items as suggested in the documentation. Something to try later in the week, unless you want to give it a go earlier.

**Comment by InBrewJ** [comment]
I probably won't have time in the week after `hopefully` getting through the jack/hdmi switch and the filetype whitelisting etc, it could be best if you stick with this for now.

Also, @bungeejim I've updated the player software for the standalone player - your `lrpi` should pick it up after a reboot. Let me know if there are any problems

**Comment by pisuke** [comment]
@InBrewJ  Cool, happy to do it my side, sure.
Are you changes just in develop or are you going to merge to master too?
Shall we do it with PRs and code reviews? I've sent you a couple earlier today, but ended up merging changes to display and bootstrap anyway (develop was actually behind master in both cases).

**Comment by InBrewJ** [comment]
@pisuke There seems to be a divergence between a few of the repos and DockerHub - I'll do an audit of everything tonight.

From what I can tell, the docker-compose.yaml in Jim's standalone box targets `lushdigital/lushroom-player:staging` rather than `lushdigital/lushroom-player:latest` - hence why I haven't merged into master yet.
