### ISSUE TITLE
Add cleaning mode

### ISSUE THREAD

**Issue by polyphantmgs** [LUSHDigital/lrpi_player#58]
We need a treatment for the cleaning mode which is easily accessable.

Call it CLEANING MODE
2 hours long

**Comment by pisuke** [comment]
Implementation note:

- Create separate audio files for cleaning modes
- Create separate srt files for cleaning modes
- Create a settings.json file that has a boolean field for loop / no_loop.

**Comment by polyphantmgs** [comment]
can we please make sure the white is warm white 3,000K ish... not the cool white?

thanks!

**Comment by pisuke** [comment]
Cleaning mode now added, with 3000K colour temperature and silent audio file.
The player already supported looping, so no need for the additional loop/no loop
