### ISSUE TITLE
menu mode

### ISSUE THREAD

**Issue by InBrewJ** [LUSHDigital/lrpi_player#91]

**Comment by InBrewJ** [comment]
when NOT playing tracks:
DMX: 
channels 1-9 70% 
channels 10-13 ZERO

**Comment by InBrewJ** [comment]
In progress by Francesco on site, notes:
DMX controller NEEDS to be set on logarithmic mode
DMX: 

MAKE INT - 65% = 0.65
channel 1: 0.65
channel 2: 0.40
channel 3: 0.40
channel 4: 0.40
channel 5: 0.40
channel 6: 0.40
channel 7: 0.40
channel 8: 0.40
channel 9: 0.40
channel 10: 0.40
channel 11: 0.40
channel 12: 0.40
channel 13:  0.40


HUE bri 50

**Comment by pisuke** [comment]
Values added to treatments menu
