### ISSUE TITLE
Make standalone player

### ISSUE THREAD

**Issue by pisuke** [LUSHDigital/lrpi_player#98]

**Comment by pisuke** [comment]
Works without network connection with DMX + with direct ethernet connection to Philips Hue + Wireless hotspot captive portal showing GUI + samba share to upload media tracks

**Comment by paulharter** [comment]
For SD card creation see:
https://github.com/arupiot/ishiki-bootstrap

For use info see:
https://docs.google.com/document/d/1c4kT5Z3GmVToqxDj9jtqiRPqPSfBmyqRGRYEY1juuvc/edit
